### ISSUE TITLE
unclickable link displayed in selector if handler page has no <title> tag 

### ISSUE THREAD

**Issue by michielbdejong** [PaulKinlan/WebIntents#139]
i know, you should always out a title tag in your page. but if you forget, while playing around to try out how to get web intents working, then this leads to an unclickable link in the selector, and you know you've done something wrong, but it's not directly clear. so maybe the selector fail more gracefully here, like user the URL or the string "Untitled" to take the place of the title.

**Comment by PaulKinlan** [comment]
Good spot.  will sort.
