### ISSUE TITLE
Intents no longer displaying in picker

### ISSUE THREAD

**Issue by glennjones** [PaulKinlan/WebIntents#146]
Hi Paul

Some changes seems to have stop my registered intents displaying in the picker. They are displayed correctly in the http://webintents.org/list.html page. You can see the issue on the page I set up for the fullfrontal demo

http://codebits.glennjones.net/webintents/contact-intent.html

You need to go to  http://codebits.glennjones.net/contact-intent/index.html  to register the intents

Debugging the live picker is really hard, any ideas on what's going on. I have an earlier version of the code (form Oct)  installed   locally that still works.

Glenn

**Comment by PaulKinlan** [comment]
I might have introduced a regression last night.
