### ISSUE TITLE
[Regression] "Done Editing" not working in Mememator

### ISSUE THREAD

**Issue by gregbillock** [PaulKinlan/WebIntents#167]
Chrome Version       : 23.0.1251.0 dev
OS Version: 6.1 (Windows 7, Windows Server 2008 R2)
URLs (if applicable) :
Other browsers tested:
Add OK or FAIL after other browsers where you have tested this issue:
Safari 5:
Firefox 4.x:
IE 7/8/9:

What steps will reproduce the problem?
1. Install Mememator, CloudFilePicker from CWS
Mememator: https://chrome.google.com/webstore/detail/lkinojipklbmjkgmmpppmbhlhfpkhmed

CloudFilePicker:
https://chrome.google.com/webstore/detail/kpeiggegnjmcinljkdmjglpjopdjihff
1. Open http://www.imagemator.com/ and click to pick an image.
2. Choose "pick image from CloudFilePicker"
3. Select an image from your machine or the web
4. Then click "Edit" in mememator
5. Edit the image and click Done Editing

What is the expected result?
You see edited image

What happens instead?
No action

Please provide any additional information below. Attach a screenshot if
possible.

UserAgentString: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.8 (KHTML, like Gecko) Chrome/23.0.1247.1 Safari/537.8

23.0.1240.0 - good build
23.0.1241.0 - bad build

See crbug.com/145821

**Comment by PaulKinlan** [comment]
This works and I can't reproduce this issue.
