### ISSUE TITLE
Web Intents CloudFilePicker example app not working in Win7

### ISSUE THREAD

**Issue by gregbillock** [PaulKinlan/WebIntents#173]
Version: 20.0.1105.0
OS: Win 7

What steps will reproduce the problem?
1. Install Mememator: https://chrome.google.com/webstore/detail/lkinojipklbmjkgmmpppmbhlhfpkhmed
2. Install CloudFilePicker: https://chrome.google.com/webstore/detail/kpeiggegnjmcinljkdmjglpjopdjihff
3. Click on image in Mememator and select CloudFilePicker from dialog

What is the expected output? What do you see instead?
- Expect to see the "Select a file" dialog in cloudfilepicker
- Instead see a blank white dialog

Works correctly on 19.0.1084.24, broken in 20.0.1105.0. So is a regression, but only in the example app, not necessarily in Chrome. Let me know if it is a Chrome regression rather than an app regression and needs a finer regression window.

Works correctly on Linux and Mac on 20.0.1105.0

See crbug.com/123890

**Comment by PaulKinlan** [comment]
Unable to reproduce.  The Picker code is out of the control of this app.
