### ISSUE TITLE
Broken link under "Received Image" in Save Intent

### ISSUE THREAD

**Issue by gregbillock** [PaulKinlan/WebIntents#176]
Chrome Version       : 21.0.1155.2 (Official Build 139341) m
URLs (if applicable) :
Other browsers tested:
Add OK or FAIL after other browsers where you have tested this issue:
Safari 5:
Firefox 4.x:
IE 7/8/9:

What steps will reproduce the problem?
1. Install Cloud File Picker, saveintent from Web Intents test plan:
https://sites.google.com/a/google.com/chrome-te/web-intents
1. Launch Chrome and open http://www.imagemator.com/
2. Click to pick an image. Choose Cloud File Picker
3. Select an image
4. Click "Save" in Imagemator and choose "Save Test Image"

What is the expected result?
Image code should be displayed under "Received Image"

See crbug.com/130177

**Comment by PaulKinlan** [comment]
Unable to reproduce
