### ISSUE TITLE
Sign-in issue with CloudFilePicker

### ISSUE THREAD

**Issue by gregbillock** [PaulKinlan/WebIntents#177]
Chrome Version       : 22.0.1229.6 (Official Build 151414) m
URLs (if applicable) :
Other browsers tested:
Add OK or FAIL after other browsers where you have tested this issue:
Safari 5:
Firefox 4.x:
IE 7/8/9:

What steps will reproduce the problem?

Install CloudFilePicker from
https://chrome.google.com/webstore/detail/kpeiggegnjmcinljkdmjglpjopdjihff
1. Launch Chrome. Make sure you are not signed-into Chrome or logged into any Google account
2. Open http://www.imagemator.com/
3. Click to pick an image and choose "pick file from CloudFilePicker"
4. It will open cloudfilepicker.com in a new tab and ask you to sign-in. Click on Sign-in. A login window appears.
5. Login using any Google account

What is the expected result?
It shows you are logged in and displays a list of images to choose from

What happens instead?
It shows empty login window or sometimes gives an error. But if you refresh the page, it shows you are logged in.

See crbug.com/142719

**Comment by PaulKinlan** [comment]
Just tested, it works right now.  I think this was an internal build of the login that was breaking.
