### ISSUE TITLE
Quick Tweet example

### ISSUE THREAD

**Issue by electerious** [PaulKinlan/WebIntents#53]
The Quick Tweet example (http://www.webintents.com/demo/simpleurlapp.html) which is linked on the main site doesn't work for me. I tried it in Firefox, Safari and Opera (all up to date) but I can't choose a service. For me it looks like that: http://s.electerious.com/Quick_Tweet-20110708-194909.png

The console says:
Creating Application Cache with manifest http://webintents.appspot.com/app.cache
Application Cache Checking event
Application Cache Error event: Failed to parse manifest http://webintents.appspot.com/app.cache

System:
Mac OS X 10.6.8

**Comment by PaulKinlan** [comment]
Ah - now I understand.  That is the old project.  Check out webintents.org.
