### ISSUE TITLE
Failure on "Shorten"

### ISSUE THREAD

**Issue by BenTrem** [PaulKinlan/WebIntents#61]
Using FF5
http://examples.webintents.org/intents/shorten/index.html
- Clicked button ... http://webintents.org/picker.html opens ... 
- Nothing listed; nothing to choose; nothing happens. 
- Clicking "View Applications" opens http://webintents.org/list.html back in the browser.  "Clear All" is the only item.
- Clicking that link does ... dunno. 
- Back on Shorten, nothing shows up after "Response will appear here:"

/bdt

**Comment by PaulKinlan** [comment]
The internal format of the webintents systems has changed, I think there must be an error.  I also need to spruce up the list page.

**Comment by BenTrem** [comment]
Ok. Occam just whispered, "Something simple got disconnected."
I know nothing about your webpages and less about your system so :-)
