### ISSUE TITLE
Rename window.navigator.startActivity to Intent.prototype.start

### ISSUE THREAD

**Issue by seaneagan** [PaulKinlan/WebIntents#68]
Compare the following:
- `window.navigator.startActivity(intent);`
- `intent.start();`

The second one is:
- shorter
- easier to remember
- cleaner (API is contained within the Intent namespace)

**Comment by PaulKinlan** [comment]
Let me raise this and see where we go.  The current theory is to keep it similar to registerProtocolHandler.

**Comment by seaneagan** [comment]
I think for flexibility's sake it would be good to avoid naming what sort of entities are used to handle intents.  Looking at the existing android APIs for kicking off intents, "startActivity" implies that "activities" handle intents, "startService" implies that "services" handle intents, "sendBroadcast" however does not imply any specific handler entity, and thus is better in this regard, it is somewhat redundant though, which could be resolved by shortening it to just "broadcast":

```
new Intent(action, type, data).broadcast();
```

If there is a desire to keep this API off of the Intent instances, it could still be kept within the Intent namespace by placing it on the constructor:

```
Intent.broadcast(new Intent(action, type, data));
```

**Comment by PaulKinlan** [comment]
The issue I have with this is that just broadcast as the API is that in the Android sense at least broadcast is for 1 app to many handlers - and our first implementation of Web Intents will only be about starting one single activitiy.  In the future I want to see the 1 to many nature of broadcast in the aPI.

**Comment by seaneagan** [comment]
I think multiple services generally make sense when the intent client is not expecting an actual data result back from postResult.  I think this is generally determined by the "action" associated with the intent.  For example, http://webintents.org/pick clients expect to receive the picked data back from postResult, and thus it doesn't make sense to invoke multiple services.  However, http://webintents.org/share clients should only need an indication of success at the most.  Also, users often share content via multiple services, and clients will want their users to be able to do this for sure.  One potential mitigant would be http://webintents.org/share implementing services similar to addthis.com or addtoany.com except that the end user rather than the developer chooses the preferred sharing services to proxy to.  However, such services would only solve the multiple intent service issue for the "share" action, rather than standardizing a solution that works for all actions.  Also, the nonexistence of such services today may indicate difficulties in their implementation.

In order for the system to determine this, action urls could define metadata as to what implementing services should return from "postResult" if anything, and that this could be used to determine whether intents with the given action can invoke multiple services.  Actually, there is probably a lot of useful metadata that could be defined for actions, which could be embedded within or linked to from the action's url.

Regarding the API name, `window.navigator.startActivity`, the "Activity" part seems to refer to basically the same thing as "action" from `intent.action` and `<intent action=...>`, and also the terms are very similar themselves.  The term "activity" also may cause confusion related to "activity streams".  Sans changing to a more generic term such as "broadcast" or "start", I think "startAction" would still be an improvement.

Regardless of the API name though, the API location seems to make more sense as `Intent` or `Intent.prototype` than `window.navigator`.

Thanks for your time!

**Comment by PaulKinlan** [comment]
Just tracking this back.  We have decided to go with window.navigator.startActivity()
