### ISSUE TITLE
Issues with non Chrome browsers

### ISSUE THREAD

**Issue by glennjones** [PaulKinlan/WebIntents#74]
Hi Paul

Was playing with the code and came across a couple of small points in the code, which seems to stop things working in the other browsers.
1. document.location.origin does not seem to be supported across all the browsers and cause problems where it is used. Mainly in picker.js where the line window.postMessage(JSON.stringify(data), document.location.origin);  as it returns undefind in Firefox etc
2. The setText() function in contoller.js does not seem work. I changed it to DOM append and it worked across the other browsers  i.e.
   
   setText(actionLink, action.title);
   to
   actionLink.appendChild(document.createTextNode(action.title));

I have only tested the link and image share intents. Hope this is useful 

Glenn Jones

**Comment by PaulKinlan** [comment]
Thanks will sort.
